services:
  - type: worker
    name: polyglot-dict-bot
    env: python
    buildCommand: pip3 install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
